export type Project = {
  id: string;
  index: string;
  name: string;
  navName: string;
  role: string;
  context: string;
  summary: string;
  evidence: string[];
  boundary: string;
  source: string;
  caseStudy?: string;
  media: { src: string; alt: string; caption: string; secondary?: { src: string; alt: string } };
  layout: "text-left" | "media-left" | "split" | "community";
};

export const projects: Project[] = [
  { id: "kairos", index: "01", name: "KAIROS", navName: "KAIROS", role: "Team Lead", context: "COMPFEST 18 AI Innovation Challenge, 2026", summary: "Dispatcher decision-support for reviewing pickup promises within limited human review capacity.", evidence: ["CatBoost ranking evaluated on public LaDe pickup data.", "Personal work: input validation, invariant tests and reproducibility records."], boundary: "The dispatcher retains the operational decision. Team-built local competition MVP.", source: "https://github.com/vlnvn/kairos-ai", caseStudy: "/work/kairos", layout: "text-left", media: { src: "/media/kairos/queue-desktop.png", alt: "KAIROS local replay interface showing an ordered pickup-review queue and review capacity cutoff", caption: "Local replay · public LaDe pickup data" } },
  { id: "ayam-kalintang", index: "02", name: "Ayam Kalintang", navName: "AYAM KALINTANG", role: "Full-Stack Engineer · Deputy Team Lead", context: "Bakti BCA · Jan–Jul 2026", summary: "Self-order kiosk and staff tools built for Ayam Kalintang, a local culinary business.", evidence: ["Personal work across kiosk, admin and menu-customization flows.", "Receipt printing and revisions from user-acceptance feedback."], boundary: "Completed July 2026 for a real local business.", source: "https://github.com/Faruuuqqq/project-bca", caseStudy: "/work/ayam-kalintang", layout: "media-left", media: { src: "/media/kalintang/kiosk-menu-desktop.png", alt: "Ayam Kalintang self-order kiosk menu showing real menu items and ordering controls", caption: "Kiosk interface · July 2026" } },
  { id: "sambut", index: "03", name: "SAMBUT", navName: "SAMBUT", role: "AI, backend & frontend contributor", context: "GEMASTIK XIX, 2026", summary: "Patient and staff terminal interfaces for a Puskesmas registration workflow.", evidence: ["Contributed across the AI, backend and frontend implementation.", "Separate patient and staff terminals coordinate the registration interaction."], boundary: "Team-built prototype. The active detector is YOLO11n; MediaPipe/BiLSTM remains a future research path.", source: "https://github.com/Phsoderma/sambut-fe", layout: "split", media: { src: "/media/sambut/patient-desktop.png", alt: "SAMBUT patient terminal interface for beginning a Puskesmas registration interaction", caption: "Patient terminal · local in-memory session · detector disabled", secondary: { src: "/media/sambut/staff-desktop.png", alt: "SAMBUT staff terminal displaying a registration queue and patient details" } } },
  { id: "colors", index: "04", name: "The Colors of MIPA", navName: "COLORS", role: "External Relations", context: "BEM FMIPA Universitas Padjadjaran", summary: "A student project involving all nine undergraduate programs in FMIPA.", evidence: ["Coordinated 30+ contributors across all 9 undergraduate programs.", "Engagement target: 200 likes. Result: 1,002 likes."], boundary: "Participation and engagement figures are from the completed campus project.", source: "https://www.instagram.com/reel/DL_5D0XxNnq/", layout: "community", media: { src: "/media/colors/reel-poster.png", alt: "Verified still from The Colors of MIPA Instagram Reel showing student contributors", caption: "Real project artifact · Instagram Reel" } },
  { id: "aether3d", index: "05", name: "Aether3D", navName: "AETHER3D", role: "Personal AI/3D experiment", context: "Independent project", summary: "A Gemini request becomes Blender Python and a simplified browser preview.", evidence: ["The workflow connects a natural-language request to generated Blender Python.", "The browser view gives a lightweight preview of the intended scene."], boundary: "The browser preview is a proxy. It is not executed Blender geometry.", source: "https://github.com/vlnvn/aether3d", layout: "media-left", media: { src: "/media/aether3d/desktop.png", alt: "Aether3D browser interface with a simplified three-dimensional scene preview and generated code", caption: "Simplified browser preview / proxy" } },
  { id: "nara", index: "06", name: "N.A.R.A.", navName: "N.A.R.A.", role: "Full-Stack & UI/UX Engineering", context: "Team project", summary: "A nutrition-planning interface connected to a Python recommendation service.", evidence: ["Built onboarding, dashboard and profile flows.", "Mapped recommendation responses and persisted meal plans."], boundary: "The recommendation engine was team-owned. No medical outcome claims are made.", source: "https://github.com/ZeitakuXIV/nara-ai", layout: "text-left", media: { src: "/media/nara/dashboard-desktop.png", alt: "N.A.R.A. dashboard showing a generated meal-plan interface", caption: "Dashboard and meal-plan flow", secondary: { src: "/media/nara/onboarding-secondary.png", alt: "N.A.R.A. onboarding interface on a mobile viewport" } } },
];

export const siteLinks = { github: "https://github.com/vlnvn", linkedin: "https://linkedin.com/in/valensiusalven", email: "mailto:alvenvalensius93@gmail.com" };
